/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;

public class LambdaHandler {

    public String myHandler(LambdaInput lambdaInput, Context context) {

        LambdaLogger logger = context.getLogger();

        try{
            String message = lambdaInput.getMessage();
            logger.log("message: " + lambdaInput.getMessage());

            return "INFO: We received your message";
        }
        catch (Exception ex) {
            ex.printStackTrace();

            return "ERROR: We are having trouble to process your message";
        }
    }
}
